### ISSUE TITLE
Extend to use with fewer than 21 points

### ISSUE THREAD

**Issue by mitchute** [knaidoo29/mistree#15]
The following throws a `ValueError`.

```
>>> import numpy as np
>>> import mistree as mist
>>> x = np.random.random_sample(20)
>>> y = np.random.random_sample(20)
>>> mst = mist.GetMST(x=x, y=y)
>>> mst.get_stats()
...
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 20, n_neighbors = 21
```

I'm not seeing this limitation spelled out in the docs, but perhaps I missed it.

**Comment by knaidoo29** [comment]
Hi @mitchute , so this error is occuring because mistree uses a k-nearest neighbour graph first, and then constructs the MST from this graph. The default settings for mistree looks for the 20 nearest neighbours. Since you have 20 points in total each point only has 19 neighbours and that's why this error is popping up. There is an error in the error message though, it's a little missleading so thanks for pointing this out. I'll try to correct that.

But to get it working for less that 20 points is fairly simple. You just need to specify the number of neighbours requested.

`
import numpy as np
import mistree as mist

x = np.random.random_sample(20)
y = np.random.random_sample(20)
mst = mist.GetMST(x=x, y=y)
# This is the crucial bit:
mst.define_k_neighbours(len(x)-1)
# This will set the k nearest neighbours to k = len(x) - 1 = 19 in your case.
# I don't recommend doing this for large samples as part of the speed up for mistree is kNN approximation. 
mst.get_stats()
`

Let me know if that works.

**Comment by mitchute** [comment]
Thanks for the reply and suggested fix - that does solve the problem. Feel free to close this issue.
