### ISSUE TITLE
How to report issues

### ISSUE THREAD

**Issue by zonca** [knaidoo29/mistree#6]
Now you mention to email you directly both at https://github.com/knaidoo29/mistree#contact and https://knaidoo29.github.io/mistreedoc/#support.
What about instead asking people to open issues via github at: https://github.com/knaidoo29/mistree/issues

**Comment by knaidoo29** [comment]
I've changed this now (included in the support section of the README and documentation) so that issues are reported through github but I've kept my email there for people who don't have a github account (or don't want one) or for whatever reason don't want the issue to be public.

> If you have any issues with the code or want to suggest ways to improve it please open a new issue (here) or (if you don't have a github account) email krishna.naidoo.11@ucl.ac.uk.

The here is a hyperlink to https://github.com/knaidoo29/mistree/issues
