### ISSUE TITLE
pip version is not importable: cannot import name 'utility_random_walk'

### ISSUE THREAD

**Issue by melissawm** [knaidoo29/mistree#8]
I installed mistree via `pip install mistree` and when I try to import it I get this error:

`ImportError: cannot import name 'utility_random_walk'`

**Comment by knaidoo29** [comment]
Hi @melissawm, I'm wondering if this is caused by me incorrectly uploading mistree 1.1.2 to pip. I've redone this to check. Could you try:

pip install mistree==1.1.3

It seems to be working on my end. The only other thing that I can think of is that the fortran subroutines are not compiling which usually means the setup can't find a fortran compiler.

**Comment by melissawm** [comment]
After cleaning up my environment and reinstalling, it works. I don't know what happened but apparently it's solved :)

**Comment by knaidoo29** [comment]
Great! I think this may be an issue with finding a fortran compiler. I had a similar issue trying to install it on a computer cluster and it was caused by me failing to load gfortran and then having a clash between python installs.
